_wandb:
    value:
        cli_version: 0.21.1
        e:
            pdkjg4tqoe1eo3oqxxdkxq8oqp76bjio:
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "21474836480"
                        used: "504627200"
                email: thomas.grytnes+m8xa7mfr@posteo.net
                executable: /usr/bin/python3
                git:
                    commit: 4d7ab22a7f1383e962be73ac2155839b43c28e38
                    remote: git@github.com:tgrytnes/cnn-cancer-detection.git
                gpu: NVIDIA A40
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-0156575d-ec4e-e9df-eff1-f1e14f8a7760
                host: cea72a581dff
                memory:
                    total: "540644179968"
                os: Linux-6.8.0-59-generic-x86_64-with-glibc2.35
                program: workspace/cnn_cancer_detection_template 5.ipynb
                python: CPython 3.11.0rc1
                root: /workspace
                startedAt: "2025-08-09T05:23:17.694362Z"
                writerId: pdkjg4tqoe1eo3oqxxdkxq8oqp76bjio
        m: []
        python_version: 3.11.0rc1
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 3
                - 8
                - 13
                - 62
            "4": 3.11.0rc1
            "5": 0.21.1
            "8":
                - 1
            "10":
                - 9
                - 17
            "12": 0.21.1
            "13": linux-x86_64
